# Generated by Django 4.2.3 on 2023-07-11 14:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='desc_image', verbose_name='Картинка gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbank', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
