# Generated by Django 4.2.3 on 2023-07-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0002_gallery_props_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
