# Generated by Django 4.2.3 on 2023-07-15 08:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0003_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us_mainpaig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField(null=True)),
                ('text_ky', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Текст внизу главной страницы',
                'verbose_name_plural': 'Текст внизу главной страницы',
            },
        ),
    ]
