# Generated by Django 4.2.3 on 2023-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0005_email_partner_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название случая')),
                ('description_title', models.TextField()),
                ('image_title', models.ImageField(upload_to='help_cases/')),
                ('image_slider_1', models.ImageField(upload_to='help_cases/')),
                ('image_slider_2', models.ImageField(upload_to='help_cases/')),
                ('description_full', models.TextField()),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('contact', models.CharField(max_length=200, verbose_name='Контактный номер')),
                ('requisites', models.CharField(max_length=200, verbose_name='Реквизиты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Случай помощи',
                'verbose_name_plural': 'Случаи помощи',
            },
        ),
    ]
