# Generated by Django 4.2.3 on 2023-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0007_helpcase_address_ky_helpcase_address_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcase',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='address_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='address_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='image_slider_1',
            field=models.ImageField(blank=True, null=True, upload_to='help_cases/'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='image_slider_2',
            field=models.ImageField(blank=True, null=True, upload_to='help_cases/'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='help_cases/'),
        ),
        migrations.AlterField(
            model_name='helpcase',
            name='requisites',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Реквизиты'),
        ),
    ]
