# Generated by Django 4.2.3 on 2023-07-16 15:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0008_alter_helpcase_address_alter_helpcase_address_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_page_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField(null=True)),
                ('text_ky', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'Текст в самой странице о нас',
                'verbose_name_plural': 'Текст в самой странице о нас',
            },
        ),
    ]
