# Generated by Django 4.2.3 on 2023-07-18 00:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0009_about_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page_text',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us_mainpaig',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='helpcase',
            name='address_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='helpcase',
            name='description_full_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helpcase',
            name='description_title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='helpcase',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название случая'),
        ),
    ]
