# Generated by Django 4.2.3 on 2023-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0010_about_page_text_text_en_about_us_mainpaig_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page_text',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help_cases/'),
        ),
    ]
