# Generated by Django 4.2.3 on 2023-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0011_about_page_text_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Картинки галлереи', 'verbose_name_plural': 'Картинки галлереи'},
        ),
        migrations.AlterModelOptions(
            name='props',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='help_cases/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Название случая'),
            preserve_default=False,
        ),
    ]
