# Generated by Django 4.2.3 on 2023-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0012_alter_gallery_options_alter_props_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название картинки'),
        ),
    ]
