# Generated by Django 4.2.3 on 2023-07-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0015_gallery_10_gallery_11_gallery_12_gallery_3_gallery_4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_ky', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('low_text', models.TextField()),
                ('low_text_ru', models.TextField(null=True)),
                ('low_text_ky', models.TextField(null=True)),
                ('low_text_en', models.TextField(null=True)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name': 'Слайдер 2',
                'verbose_name_plural': 'Слайдер 1',
            },
        ),
    ]
