# Generated by Django 4.2.3 on 2023-07-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_charity', '0016_slider1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider1',
            new_name='Slider',
        ),
    ]
